Problem: missing returning of SignDoc for ledger #130
crypto-com/chain-jslib pull request #131
Opened 2021-01-20 11:11 UTC by leejw51crypto

add toSignDocRaw
this is bytes before hashing, can be used for ledger

2021-01-20 11:17 UTC, eddycpc submitted a review, later dismissed
Looks good.

2021-01-20 11:29 UTC, crypto-matto submitted a review, later dismissed
LGTM~

2021-01-22 02:05 UTC, tomtau commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
`toSignDocHash` may be a better name? this doesn't return the signdoc payload, but sha256 of signdoc payload

2021-01-25 03:27 UTC, leejw51crypto commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
not bad, i'll change it

2021-01-25 05:03 UTC, calvinaco approved these changes

2021-01-25 05:04 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
It will be better to provide this as an alias. coz changing `toSignDoc` may break some codes. @eddycpc

2021-01-25 06:00 UTC, tomtau commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
@calvinaco keep the old name with the original functionality (i.e. keep `toSignDoc` as what's in this PR `toSignDocRaw`) and name this new function that's returning the signing digest differently?
as per C4: https://rfc.zeromq.org/spec/42/#26-evolution-of-public-contracts
> Old names SHALL NOT be reused by new contracts.

2021-01-25 06:24 UTC, leejw51crypto commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
by npm version, previous published version will not be impacted, though.

2021-01-25 06:34 UTC, linfeng-crypto approved these changes

2021-01-25 06:56 UTC, leejw51crypto commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
change the names, and preserved oldname not to break legacy code

2021-01-25 06:59 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
Yes agree. To make it clear:

`toSignDocument`: New method introduced that returns the normal (Non-hashed) sign doc
`toSignDocumentHash`: New method introduced that returns hashed sign doc
`toSignDoc`: Going to be deprecated method which has the same behaviour as before (same as `toSignDocumentHash`)

2021-01-25 07:04 UTC, leejw51crypto commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
yes, i'm changing unit-test.

2021-01-25 07:22 UTC, eddycpc requested changes

2021-01-25 07:22 UTC, eddycpc commented on lib/e2e/transaction.spec.ts
> +            .setSignature(0, keyPair.sign(signableTx.toSignDocumentHash(0)))
We might have to be careful here, **this is a breaking change for all other API users**: chain desktop wallet and all other folks that have already started integrating.

2021-01-25 07:30 UTC, leejw51crypto commented on lib/e2e/transaction.spec.ts
> +            .setSignature(0, keyPair.sign(signableTx.toSignDocumentHash(0)))
toSignDoc is still supported, so this pr not break for the time being

2021-01-25 07:31 UTC, eddycpc commented on lib/e2e/transaction.spec.ts
> +            .setSignature(0, keyPair.sign(signableTx.toSignDocumentHash(0)))
Very cool if it's that way, Thanks

2021-01-25 07:31 UTC, eddycpc approved these changes

2021-01-25 07:33 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +    public toSignDoc(index: number): Bytes {
cc @eddycpc

2021-01-25 07:34 UTC, calvinaco commented
@leejw51crypto is it good to merge?

2021-01-25 07:35 UTC, leejw51crypto commented
yes

2021-01-25 07:39 UTC, merged