Problem: missing amino json of Delegate, WithdrawDelegateReward (fix …
crypto-com/chain-jslib pull request #135
Opened 2021-01-27 13:52 UTC by leejw51crypto

Solution: add raw amino json

2021-01-27 16:06 UTC, eddycpc requested changes

2021-01-27 16:06 UTC, eddycpc commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.ts
> +                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
Can you add test case for these additions ?

2021-01-28 01:28 UTC, leejw51crypto commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.ts
> +                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
ok,i will add unit test

2021-01-28 06:38 UTC, leejw51crypto commented
added unit test for coverage

2021-01-28 07:55 UTC, eddycpc approved these changes

2021-01-28 07:59 UTC, crypto-matto approved these changes
LGTM

2021-01-28 09:00 UTC, calvinaco approved these changes
LGTM

2021-01-28 09:01 UTC, calvinaco commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.ts
> +                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
I assume this is resolved @eddycpc

2021-01-28 10:01 UTC, merged