Problem: withdraw delegation reward is not working with ledger (fix #…
crypto-com/chain-jslib pull request #141
Opened 2021-02-05 08:33 UTC by leejw51crypto

Solution:
change MsgWithdrawDelegatorReward type 
from 'cosmos-sdk/MsgWithdrawDelegationReward'
to 'cosmos-sdk/MsgWithdrawDelegationReward'

2021-02-05 08:35 UTC, crypto-matto approved these changes

2021-02-05 09:36 UTC, eddycpc approved these changes

2021-02-08 01:42 UTC, linfeng-crypto approved these changes

2021-02-08 04:27 UTC, calvinaco commented
Will this affect our protobuf version of the message? Because I see it is only changed in Amino JSON version.

2021-02-08 07:15 UTC, eddycpc requested changes

2021-02-08 07:15 UTC, eddycpc commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.spec.ts
> -                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
Thanks, @calvinaco for noticing this.

This is definitely a breaking change for Protobuf delegator reward withdrawal which was working already before and didn't need to be changed here.

2021-02-08 16:27 UTC, calvinaco commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.spec.ts
> -                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
cc @leejw51crypto

2021-02-09 01:41 UTC, leejw51crypto commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.spec.ts
> -                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
i'll check

2021-02-09 01:59 UTC, leejw51crypto commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.spec.ts
> -                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
export const COSMOS_MSG_TYPEURL = {
    MsgBeginRedelegate: '/cosmos.staking.v1beta1.MsgBeginRedelegate',
    Coin: '/cosmos.base.v1beta1.Coin',
    MsgSend: '/cosmos.bank.v1beta1.MsgSend',
    MsgWithdrawDelegatorReward: '/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward',
    MsgCreateValidator: '/cosmos.staking.v1beta1.MsgCreateValidator',
    MsgEditValidator: '/cosmos.staking.v1beta1.MsgEditValidator',
    MsgDelegate: '/cosmos.staking.v1beta1.MsgDelegate',
    MsgUndelegate: '/cosmos.staking.v1beta1.MsgUndelegate',
    MsgWithdrawValidatorCommission: '/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission',
    MsgDeposit: '/cosmos.gov.v1beta1.MsgDeposit',
    MsgVote: '/cosmos.gov.v1beta1.MsgVote',
    MsgSubmitProposal: '/cosmos.gov.v1beta1.MsgSubmitProposal',
    PubKey: {
        ed25519: '/cosmos.crypto.ed25519.PubKey',
    },
};



        // eslint-disable-next-line class-methods-use-this
        toRawAminoMsg(): legacyAmino.Msg {
            return {
                type: 'cosmos-sdk/MsgWithdrawDelegationReward',
                value: {
                    delegator_address: this.delegatorAddress,
                    validator_address: this.validatorAddress,
                },
            } as legacyAmino.MsgWithdrawDelegatorReward;
        }

        /**
         * Returns the raw Msg representation of MsgWithdrawDelegatorReward
         * @returns {Msg}
         */
        toRawMsg(): Msg {
            return {
                typeUrl: COSMOS_MSG_TYPEURL.MsgWithdrawDelegatorReward,
                value: {
                    delegatorAddress: this.delegatorAddress,
                    validatorAddress: this.validatorAddress,
                },
            };
        }

2021-02-09 01:59 UTC, leejw51crypto commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.spec.ts
> -                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
protobuf used toRawMsg, it is still using '/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward',

2021-02-09 02:54 UTC, leejw51crypto commented on lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.spec.ts
> -                type: 'cosmos-sdk/MsgWithdrawDelegatorReward',
![image](https://user-images.githubusercontent.com/51560997/107309342-970d4000-6acd-11eb-979c-b23c97d6cbd2.png)

protobuf
withdraw delegator reward, working fine

2021-02-09 06:03 UTC, calvinaco approved these changes

2021-02-09 06:31 UTC, eddycpc approved these changes

2021-02-09 06:43 UTC, merged